// Games that light RGB gear through a vendor's lighting SDK, from the public lists: Razer's
// Chroma Workshop (its games.json, the list Razer's site shows), Logitech's LIGHTSYNC games,
// Corsair's iCUE games, SteelSeries' GameSense games, Dell's AlienFX games and ASUS' Aura Sync
// games (gathered on PCGamingWiki's "RGB lighting middleware" page and the community LIGHTSYNC
// list). LumaBridge answers each of these SDKs, so these games light
// every device once the SDK is set up on the Integrations page. game_profiles.h turns each row
// into a profile; games with a hand-written profile there (Battlefield, Apex, ...) aren't
// repeated here. Matched by exe name when it's known, else by the game's name.
#pragma once

namespace luma::app::games {

enum SdkBit : unsigned {
    kChroma = 1,      // Razer Chroma
    kLightsync = 2,   // Logitech LIGHTSYNC (LED SDK)
    kIcue = 4,        // Corsair iCUE (CUE SDK)
    kGameSense = 8,   // SteelSeries GameSense
    kAlienFx = 16,    // Alienware AlienFX (LightFX)
    kAura = 32,       // ASUS Aura Sync: the game drives Aura itself, LumaBridge can't catch it
};

struct SdkGame {
    const char* title;
    unsigned sdks;           // SdkBit
    const char* exe;         // lower case, or nullptr when not known
    const char* exe2;
    const char* alias;       // another name the game goes by, or nullptr
};

inline const SdkGame* SdkGames(size_t* count) {
    constexpr unsigned C = kChroma, L = kLightsync, I = kIcue, G = kGameSense, A = kAlienFx, U = kAura;
    static const SdkGame kGames[] = {
        // Well-known titles, with their exe names.
        {"Cyberpunk 2077", C, "cyberpunk2077.exe", nullptr, nullptr},
        {"Baldur's Gate 3", C, "bg3.exe", "bg3_dx11.exe", nullptr},
        {"Fortnite", C | L, "fortniteclient-win64-shipping.exe", nullptr, nullptr},
        {"Diablo IV", C, "diablo iv.exe", nullptr, "Diablo 4"},
        {"Diablo III", C | I, "diablo iii64.exe", "diablo iii.exe", "Diablo 3"},
        {"World of Warcraft", C, "wow.exe", nullptr, nullptr},
        {"FINAL FANTASY XIV Online", C | L, "ffxiv_dx11.exe", nullptr, "Final Fantasy XIV"},
        {"FINAL FANTASY XV WINDOWS EDITION", C | A, "ffxv_s.exe", nullptr, "Final Fantasy XV"},
        {"FINAL FANTASY XVI", C, "ffxvi.exe", nullptr, nullptr},
        {"Halo Infinite", C, "haloinfinite.exe", nullptr, nullptr},
        {"Hogwarts Legacy", C, "hogwartslegacy.exe", nullptr, nullptr},
        {"Warframe", C, "warframe.x64.exe", nullptr, nullptr},
        {"Minecraft for Windows", C, "minecraft.windows.exe", nullptr, "Minecraft: Bedrock Edition"},
        {"The Elder Scrolls Online", C, "eso64.exe", nullptr, "Elder Scrolls Online"},
        {"Gears 5", C, "gears5.exe", nullptr, nullptr},
        {"DOOM", C, "doomx64.exe", "doomx64vk.exe", nullptr},
        {"Hunt: Showdown 1896", C, "huntgame.exe", nullptr, "Hunt: Showdown"},
        {"Monster Hunter Rise", C, "monsterhunterrise.exe", nullptr, nullptr},
        {"Borderlands 3", L, "borderlands3.exe", nullptr, nullptr},
        {"Borderlands 4", C, "borderlands4.exe", nullptr, nullptr},
        {"Mortal Kombat 11", C | L | G | A, "mk11.exe", nullptr, nullptr},
        {"Killing Floor 2", C | L | A, "kfgame.exe", nullptr, nullptr},
        {"Frostpunk", C | L | A, "frostpunk.exe", nullptr, nullptr},
        {"Frostpunk 2", C, nullptr, nullptr, nullptr},
        {"Far Cry 5", I, "farcry5.exe", nullptr, nullptr},
        {"Far Cry 6", I, "farcry6.exe", nullptr, nullptr},
        {"Far Cry New Dawn", I, "farcrynewdawn.exe", nullptr, nullptr},
        {"Tom Clancy's The Division 2", I, "thedivision2.exe", nullptr, "The Division 2"},
        {"Tom Clancy's The Division", L, "thedivision.exe", nullptr, "The Division"},
        {"Tom Clancy's Ghost Recon Breakpoint", I, "grb.exe", "grb_vulkan.exe", "Ghost Recon Breakpoint"},
        {"Metro Exodus", I, "metroexodus.exe", nullptr, "Metro Exodus Enhanced Edition"},
        {"Tiny Tina's Wonderlands", I, "wonderlands.exe", nullptr, nullptr},
        {"Sifu", I, "sifu.exe", nullptr, nullptr},
        {"Subnautica: Below Zero", I, "subnauticazero.exe", nullptr, nullptr},
        {"Mass Effect: Andromeda", L, "masseffectandromeda.exe", nullptr, nullptr},
        {"Mass Effect 3", A, "masseffect3.exe", nullptr, nullptr},
        {"STAR WARS Battlefront II", L, "starwarsbattlefrontii.exe", nullptr, nullptr},
        {"Anthem", L | U, "anthem.exe", nullptr, nullptr},
        {"Mafia III", L | A, "mafia3.exe", nullptr, "Mafia III: Definitive Edition"},
        {"Mafia: Definitive Edition", G, "mafiadefinitiveedition.exe", nullptr, nullptr},
        {"Last Epoch", L, "last epoch.exe", nullptr, nullptr},
        {"Kerbal Space Program", C, "ksp_x64.exe", nullptr, nullptr},
        {"Kerbal Space Program 2", L, "ksp2_x64.exe", nullptr, nullptr},
        {"Dead Cells", C, "deadcells.exe", nullptr, nullptr},
        {"Stardew Valley", C, "stardew valley.exe", nullptr, nullptr},
        {"Deep Rock Galactic", C, "fsd-win64-shipping.exe", nullptr, nullptr},
        {"Deus Ex: Mankind Divided", C, "dxmd.exe", nullptr, nullptr},
        {"Rise of the Tomb Raider", C, "rottr.exe", nullptr, nullptr},
        {"HITMAN 2", C, "hitman2.exe", nullptr, nullptr},
        {"RAGE 2", C, "rage2.exe", nullptr, nullptr},
        {"Just Cause 4", C, "justcause4.exe", nullptr, nullptr},
        {"Quake Champions", C, "quakechampions.exe", nullptr, nullptr},
        {"Call of Duty: Black Ops III", C, "blackops3.exe", nullptr, nullptr},
        {"Call of Duty: WWII", L, nullptr, nullptr, nullptr},
        {"Dying Light", A, "dyinglightgame.exe", nullptr, nullptr},
        {"Kingdom Come: Deliverance", A, "kingdomcome.exe", nullptr, nullptr},
        {"Guild Wars 2", A, "gw2-64.exe", nullptr, nullptr},
        {"PAYDAY 2", A, "payday2_win32_release.exe", nullptr, nullptr},
        {"Stellaris", A, "stellaris.exe", nullptr, nullptr},
        {"World of Tanks", A, "worldoftanks.exe", nullptr, nullptr},
        {"World of Warships", C, "worldofwarships64.exe", nullptr, nullptr},
        {"Black Desert", C | A, "blackdesert64.exe", nullptr, "Black Desert Online"},
        {"Gotham Knights", C, nullptr, nullptr, nullptr},
        {"Forspoken", C, nullptr, nullptr, nullptr},
        {"UNCHARTED: Legacy of Thieves Collection", C, "u4.exe", "tll.exe", nullptr},
        {"SILENT HILL 2", C, nullptr, nullptr, nullptr},
        {"S.T.A.L.K.E.R. 2: Heart of Chornobyl", C, nullptr, nullptr, nullptr},
        {"Dune: Awakening", C, nullptr, nullptr, nullptr},
        {"Once Human", C, nullptr, nullptr, nullptr},
        {"Outriders", C, nullptr, nullptr, nullptr},
        {"Remnant: From the Ashes", C, nullptr, nullptr, nullptr},
        {"Gears Tactics", C, nullptr, nullptr, nullptr},
        {"Ghostrunner", I | U, nullptr, nullptr, nullptr},
        {"Ghostrunner 2", C, nullptr, nullptr, nullptr},
        {"Injustice 2", C | L, nullptr, nullptr, nullptr},
        {"Neverwinter", C | I | G | A, nullptr, nullptr, nullptr},
        {"Warhammer: Vermintide 2", C | A, nullptr, nullptr, nullptr},
        {"SnowRunner", C, nullptr, nullptr, nullptr},
        {"House Flipper", C, nullptr, nullptr, nullptr},
        {"PC Building Simulator 2", C, nullptr, nullptr, nullptr},
        {"Divinity: Original Sin 2", C, nullptr, nullptr, "Divinity: Original Sin 2 - Definitive Edition"},
        {"Pathfinder: Wrath of the Righteous", C, nullptr, nullptr, nullptr},
        {"MechWarrior 5: Mercenaries", C, nullptr, nullptr, nullptr},
        {"MechWarrior 5: Clans", C, nullptr, nullptr, nullptr},
        {"Total War: WARHAMMER II", L, "warhammer2.exe", nullptr, nullptr},
        {"Battlefield Hardline", L, nullptr, nullptr, nullptr},
        {"Mirror's Edge Catalyst", L, nullptr, nullptr, nullptr},
        {"Borderlands: The Pre-Sequel", L, nullptr, nullptr, nullptr},
        {"Homefront: The Revolution", L | I, nullptr, nullptr, nullptr},
        {"Squad", L, "squadgame.exe", nullptr, nullptr},
        {"Unreal Tournament", C | I, nullptr, nullptr, nullptr},

        // Razer Chroma (Chroma Workshop).
        {"1993 Space Machine", C, nullptr, nullptr, nullptr},
        {"A Hat in Time", C, nullptr, nullptr, nullptr},
        {"AVICII Invector", C, nullptr, nullptr, nullptr},
        {"Ancestors Legacy", C, nullptr, nullptr, nullptr},
        {"Archaica: The Path of Light", C, nullptr, nullptr, nullptr},
        {"ArcheAge", C, nullptr, nullptr, nullptr},
        {"Arise: A Simple Story", C, nullptr, nullptr, nullptr},
        {"Armored Warfare", C, nullptr, nullptr, nullptr},
        {"Aspire: Ina's Tale", C, nullptr, nullptr, nullptr},
        {"Astellia", C, nullptr, nullptr, nullptr},
        {"Atlas Reactor", C, nullptr, nullptr, nullptr},
        {"Aven Colony", C, nullptr, nullptr, nullptr},
        {"Badass Hero", C, nullptr, nullptr, nullptr},
        {"Bake 'n Switch", C, nullptr, nullptr, nullptr},
        {"Battle Chasers: Nightwar", C, nullptr, nullptr, nullptr},
        {"Battlerite", C, nullptr, nullptr, nullptr},
        {"Battlerite Royale", C, nullptr, nullptr, nullptr},
        {"Battlezone 98 Redux", C, nullptr, nullptr, nullptr},
        {"Black Ice", C, nullptr, nullptr, nullptr},
        {"Black The Fall", C, nullptr, nullptr, nullptr},
        {"Blade & Soul", C, nullptr, nullptr, nullptr},
        {"Bless Unleashed", C, nullptr, nullptr, nullptr},
        {"Book of Demons", C | L | G, nullptr, nullptr, nullptr},
        {"BAFL - Brakes Are For Losers", C, nullptr, nullptr, nullptr},
        {"Bright Paw", C, nullptr, nullptr, nullptr},
        {"Cat Quest", C, nullptr, nullptr, nullptr},
        {"Cat Quest II", C, nullptr, nullptr, "Cat Quest 2"},
        {"Clicker Heroes", C, nullptr, nullptr, nullptr},
        {"Code 7", C, nullptr, nullptr, nullptr},
        {"Coffee Crisis", C, nullptr, nullptr, nullptr},
        {"Crysis Remastered", C, nullptr, nullptr, nullptr},
        {"Dauntless", C, nullptr, nullptr, nullptr},
        {"Deceive Inc.", C, nullptr, nullptr, nullptr},
        {"Deliver Us The Moon", C, nullptr, nullptr, nullptr},
        {"Door Kickers 2: Task Force North", C, nullptr, nullptr, nullptr},
        {"Double Kick Heroes", C, nullptr, nullptr, nullptr},
        {"Dr. Fetus' Mean Meat Machine", C, nullptr, nullptr, nullptr},
        {"DREDGE", C, nullptr, nullptr, nullptr},
        {"Driftland: The Magic Revival", C, nullptr, nullptr, nullptr},
        {"Dropzone", C, nullptr, nullptr, nullptr},
        {"DubWars", C, nullptr, nullptr, nullptr},
        {"Duelyst", C, nullptr, nullptr, nullptr},
        {"Dungeon Souls", C | A, nullptr, nullptr, nullptr},
        {"ELEX", C, nullptr, nullptr, nullptr},
        {"Endless Dungeon", C, nullptr, nullptr, nullptr},
        {"Endless Space 2", C, nullptr, nullptr, nullptr},
        {"Empire of Sin", C, nullptr, nullptr, nullptr},
        {"Epsilon", C, nullptr, nullptr, nullptr},
        {"Escape from Naraka", C, nullptr, nullptr, nullptr},
        {"Evolve Stage 2", C, nullptr, nullptr, nullptr},
        {"Exoprimal", C, nullptr, nullptr, nullptr},
        {"F1 Manager 2022", C, nullptr, nullptr, nullptr},
        {"Firmament", C, nullptr, nullptr, nullptr},
        {"Fisti-Fluffs", C, nullptr, nullptr, nullptr},
        {"Foreclosed", C, nullptr, nullptr, nullptr},
        {"Formula Fusion", C, nullptr, nullptr, nullptr},
        {"Freaky Awesome", C, nullptr, nullptr, nullptr},
        {"Fruit Factory", C, nullptr, nullptr, nullptr},
        {"Georifters", C, nullptr, nullptr, nullptr},
        {"Gigantic", C, nullptr, nullptr, "Gigantic: Rampage Edition"},
        {"Gigapocalypse", C, nullptr, nullptr, nullptr},
        {"Glitch's Trip", C, nullptr, nullptr, nullptr},
        {"God's Trigger", C | A, nullptr, nullptr, nullptr},
        {"Godstrike", C, nullptr, nullptr, nullptr},
        {"Gori: Cuddly Carnage", C, nullptr, nullptr, nullptr},
        {"Gord", C, nullptr, nullptr, nullptr},
        {"Harlow", C, nullptr, nullptr, nullptr},
        {"Hellcard", C, nullptr, nullptr, nullptr},
        {"Hell Pie", C, nullptr, nullptr, nullptr},
        {"Holy Potatoes! What the Hell?!", C, nullptr, nullptr, nullptr},
        {"Hover", C | A, nullptr, nullptr, "Hover: Revolt of Gamers"},
        {"Hue", C, nullptr, nullptr, nullptr},
        {"Hunt the Night", C, nullptr, nullptr, nullptr},
        {"I, Zombie", C, nullptr, nullptr, nullptr},
        {"Immortal: Unchained", C, nullptr, nullptr, nullptr},
        {"Infinity Strash: DRAGON QUEST The Adventure of Dai", C, nullptr, nullptr, nullptr},
        {"Iron Harvest", C, nullptr, nullptr, nullptr},
        {"JCB Pioneer: Mars", C, nullptr, nullptr, nullptr},
        {"Killsquad", C, nullptr, nullptr, nullptr},
        {"Kinetic Edge", C, nullptr, nullptr, nullptr},
        {"King's Bounty II", C, nullptr, nullptr, nullptr},
        {"Kosmokrats", C, nullptr, nullptr, nullptr},
        {"LEGO Bricktales", C, nullptr, nullptr, nullptr},
        {"Let Them Come", C | A, nullptr, nullptr, nullptr},
        {"Lichtspeer", C, nullptr, nullptr, nullptr},
        {"Life is Strange: True Colors", C, nullptr, nullptr, nullptr},
        {"Little Big Workshop", C, nullptr, nullptr, nullptr},
        {"Livelock", C, nullptr, nullptr, nullptr},
        {"Lost at Sea", C, nullptr, nullptr, nullptr},
        {"Main Assembly", C, nullptr, nullptr, nullptr},
        {"Martha Is Dead", C, nullptr, nullptr, nullptr},
        {"Masquerada: Songs and Shadows", C, nullptr, nullptr, nullptr},
        {"Medieval Dynasty", C, nullptr, nullptr, nullptr},
        {"Megaton Rainfall", C | A, nullptr, nullptr, nullptr},
        {"Mondrian - Plastic Reality", C, nullptr, nullptr, nullptr},
        {"Move or Die", C, nullptr, nullptr, nullptr},
        {"Myst", C, nullptr, nullptr, nullptr},
        {"Nanotale - Typing Chronicles", C, nullptr, nullptr, nullptr},
        {"Neko Ghost, Jump!", C, nullptr, nullptr, nullptr},
        {"Necronator: Dead Wrong", C, nullptr, nullptr, nullptr},
        {"Nevermind", C, nullptr, nullptr, nullptr},
        {"notmycar", C, nullptr, nullptr, nullptr},
        {"Obduction", C, nullptr, nullptr, nullptr},
        {"Observer: System Redux", C, nullptr, nullptr, nullptr},
        {"Oh...Sir! The Insult Simulator", C, nullptr, nullptr, nullptr},
        {"Orcs Must Die! Unchained", C, nullptr, nullptr, nullptr},
        {"Out There: Oceans of Time", C, nullptr, nullptr, nullptr},
        {"Outlast 2", C, nullptr, nullptr, nullptr},
        {"Paper Cut Mansion", C, nullptr, nullptr, nullptr},
        {"Phantom Doctrine", C, nullptr, nullptr, nullptr},
        {"Pigeon Fight", C, nullptr, nullptr, nullptr},
        {"Pinball FX", C, nullptr, nullptr, nullptr},
        {"Please, Don't Touch Anything 3D", C, nullptr, nullptr, nullptr},
        {"Project Genesis", C, nullptr, nullptr, nullptr},
        {"Project Nimbus", C, nullptr, nullptr, nullptr},
        {"Redout", C, nullptr, nullptr, nullptr},
        {"Rise of Insanity", C, nullptr, nullptr, nullptr},
        {"Rogue State Revolution", C, nullptr, nullptr, nullptr},
        {"RUINER", C, nullptr, nullptr, nullptr},
        {"Rumu", C, nullptr, nullptr, nullptr},
        {"Screw Drivers", C, nullptr, nullptr, nullptr},
        {"Semispheres", C | A, nullptr, nullptr, nullptr},
        {"Seven: The Days Long Gone", C, nullptr, nullptr, nullptr},
        {"Shadow Warrior 2", C | A, nullptr, nullptr, nullptr},
        {"Shovel Knight", C, nullptr, nullptr, "Shovel Knight: Treasure Trove"},
        {"Shroud of the Avatar: Forsaken Virtues", C | A, nullptr, nullptr, "Shroud of the Avatar"},
        {"Skeleton Crew", C, nullptr, nullptr, nullptr},
        {"Slaycation Paradise", C, nullptr, nullptr, nullptr},
        {"SmuggleCraft", C, nullptr, nullptr, nullptr},
        {"Sniper Elite: Resistance", C, nullptr, nullptr, nullptr},
        {"SNOW", C, nullptr, nullptr, nullptr},
        {"Spacelines from the Far Out", C, nullptr, nullptr, nullptr},
        {"Spin Rhythm XD", C, nullptr, nullptr, nullptr},
        {"Star Trek Online", C | A, nullptr, nullptr, nullptr},
        {"StarCrawlers", C, nullptr, nullptr, nullptr},
        {"Starpoint Gemini Warlords", C | L, nullptr, nullptr, nullptr},
        {"Steel Circus", C, nullptr, nullptr, nullptr},
        {"Stifled", C, nullptr, nullptr, nullptr},
        {"Stray Blade", C, nullptr, nullptr, nullptr},
        {"Super Inefficient Golf", C, nullptr, nullptr, nullptr},
        {"Super Mega Zero", C, nullptr, nullptr, nullptr},
        {"Symphonia", C, nullptr, nullptr, nullptr},
        {"Swimsanity!", C, nullptr, nullptr, nullptr},
        {"The Coma 2B: Catacomb", C, nullptr, nullptr, nullptr},
        {"The Fabled Woods", C, nullptr, nullptr, nullptr},
        {"The Last Friend", C, nullptr, nullptr, nullptr},
        {"The Little Acre", C, nullptr, nullptr, nullptr},
        {"The Riftbreaker", C, nullptr, nullptr, nullptr},
        {"The Sandbox Evolution", C, nullptr, nullptr, nullptr},
        {"The Shore", C, nullptr, nullptr, nullptr},
        {"Those Who Remain", C, nullptr, nullptr, nullptr},
        {"Thumper", C, nullptr, nullptr, nullptr},
        {"Togges", C, nullptr, nullptr, nullptr},
        {"Trove", C, nullptr, nullptr, nullptr},
        {"Trover Saves the Universe", C, nullptr, nullptr, nullptr},
        {"Unicorns on Unicycles", C, nullptr, nullptr, nullptr},
        {"Under: Depths of Fear", C, nullptr, nullptr, nullptr},
        {"Vendetta Online", C, nullptr, nullptr, nullptr},
        {"Way of the Hunter", C, nullptr, nullptr, nullptr},
        {"White Shadows", C, nullptr, nullptr, nullptr},
        {"World War Z: Aftermath", C, nullptr, nullptr, "World War Z"},
        {"Worms W.M.D", C, nullptr, nullptr, nullptr},
        {"Yet Another Zombie Defense HD", C, nullptr, nullptr, nullptr},

        // Razer Chroma, newer and more from Razer's list.
        {"Control Resonant", C, nullptr, nullptr, nullptr},
        {"GOALS", C, nullptr, nullptr, nullptr},
        {"007 First Light", C, nullptr, nullptr, nullptr},
        {"Croc: Legend of the Gobbos", C, nullptr, nullptr, "Croc Legend of the Gobbos"},
        {"Virtua Fighter 5 R.E.V.O. World Stage", C, nullptr, nullptr, "Virtua Fighter 5 R.E.V.O."},
        {"Screamer", C, nullptr, nullptr, nullptr},
        {"Super Meat Boy 3D", C, nullptr, nullptr, nullptr},
        {"Atelier Yumia: The Alchemist of Memories & the Envisioned Land", C, nullptr, nullptr, "Atelier Yumia"},
        {"Metal: Hellsinger", C, nullptr, nullptr, nullptr},
        {"Dolmen", C, nullptr, nullptr, nullptr},
        {"Keyboard Piano-ist", C, nullptr, nullptr, nullptr},
        {"Fate Trigger: The Novita", C, nullptr, nullptr, "Fate Trigger"},
        {"Mars or Die!", C, nullptr, nullptr, nullptr},
        {"GoatPunks", C, nullptr, nullptr, nullptr},
        {"Pixel: ru2", C, nullptr, nullptr, nullptr},
        {"Fractured Space", C, nullptr, nullptr, nullptr},
        {"X-Morph: Defense", C, nullptr, nullptr, nullptr},

        // Logitech LIGHTSYNC.
        {"Beat Cop", L | A, nullptr, nullptr, nullptr},
        {"Distance", L, nullptr, nullptr, nullptr},
        {"Journey to the Savage Planet", L | A, nullptr, nullptr, nullptr},
        {"Moonlighter", L, nullptr, nullptr, nullptr},
        {"The Metronomicon", L, nullptr, nullptr, "The Metronomicon: Slay the Dance Floor"},
        {"The Swords of Ditto", L, nullptr, nullptr, "The Swords of Ditto: Mormo's Curse"},

        // Corsair iCUE.
        {"Blair Witch", I | A, nullptr, nullptr, nullptr},
        {"Chernobylite", I, nullptr, nullptr, nullptr},
        {"Dwerve", I, nullptr, nullptr, nullptr},
        {"Embr", I, nullptr, nullptr, nullptr},
        {"Freshly Frosted", I, nullptr, nullptr, nullptr},
        {"Gamedec", I, nullptr, nullptr, nullptr},
        {"Grid Force", I, nullptr, nullptr, nullptr},
        {"INMOST", I, nullptr, nullptr, nullptr},
        {"Midnight Ghost Hunt", I, nullptr, nullptr, nullptr},
        {"Old World", I, nullptr, nullptr, nullptr},
        {"Overloop", I, nullptr, nullptr, nullptr},
        {"PHOGS!", I, nullptr, nullptr, nullptr},
        {"Project Winter", I, nullptr, nullptr, nullptr},
        {"Red Solstice 2: Survivors", I, nullptr, nullptr, nullptr},
        {"Serial Cleaners", I, nullptr, nullptr, nullptr},
        {"Severed Steel", I, nullptr, nullptr, nullptr},
        {"Starmancer", I, nullptr, nullptr, nullptr},
        {"Super Magbot", I, nullptr, nullptr, nullptr},
        {"Sweet Transit", I, nullptr, nullptr, nullptr},
        {"Terra Invicta", I, nullptr, nullptr, nullptr},
        {"Thymesia", I, nullptr, nullptr, nullptr},
        {"The Medium", I, nullptr, nullptr, nullptr},
        {"Tribes of Midgard", I, nullptr, nullptr, nullptr},
        {"Vesper", I, nullptr, nullptr, nullptr},

        // SteelSeries GameSense.
        {"Cake Bash", G, nullptr, nullptr, nullptr},
        {"Cardaclysm", G, nullptr, nullptr, "Cardaclysm: Shards of the Four"},
        {"Fury Unleashed", G, nullptr, nullptr, nullptr},
        {"Lumote", G, nullptr, nullptr, "Lumote: The Mastermote Chronicles"},
        {"Utopia 9 - A Volatile Vacation", G, nullptr, nullptr, nullptr},
        {"Foregone", G, nullptr, nullptr, nullptr},

        // ASUS Aura Sync (the game lights Aura gear itself).
        {"Call of Duty: Black Ops 4", U, "blackops4.exe", nullptr, nullptr},
        {"Eternity: The Last Unicorn", U, nullptr, nullptr, nullptr},
        {"Pathfinder: Kingmaker", U, nullptr, nullptr, nullptr},
        {"Serious Sam 4", U, nullptr, nullptr, nullptr},
        {"Tropico 6", U, nullptr, nullptr, nullptr},
        {"The Surge 2", U, nullptr, nullptr, nullptr},

        // Alienware AlienFX (Dell's list; mostly older games).
        {"9 Dragons", A, nullptr, nullptr, nullptr},
        {"Agents of Mayhem", A, nullptr, nullptr, nullptr},
        {"AirMech Strike", A, nullptr, nullptr, nullptr},
        {"Albino Lullaby: Episode 1", A, nullptr, nullptr, nullptr},
        {"Alien Rage - Unlimited", A, nullptr, nullptr, nullptr},
        {"Anomaly 2", A, nullptr, nullptr, nullptr},
        {"Anomaly Defenders", A, nullptr, nullptr, nullptr},
        {"APB Reloaded", A, nullptr, nullptr, nullptr},
        {"Arms Dealer", A, nullptr, nullptr, nullptr},
        {"Bad North", A, nullptr, nullptr, "Bad North: Jotunn Edition"},
        {"BATALJ", A, nullptr, nullptr, nullptr},
        {"Battle Chef Brigade", A, nullptr, nullptr, "Battle Chef Brigade Deluxe"},
        {"Battlefield 3", A, "bf3.exe", nullptr, nullptr},
        {"Beatbuddy: Tale of the Guardians", A, nullptr, nullptr, nullptr},
        {"Blacklight: Retribution", A, nullptr, nullptr, nullptr},
        {"Blacklight: Tango Down", A, nullptr, nullptr, nullptr},
        {"Blockpocalypse", A, nullptr, nullptr, nullptr},
        {"Bloodline Champions", A, nullptr, nullptr, nullptr},
        {"Broforce", A, nullptr, nullptr, nullptr},
        {"Bust-n-Rush", A, nullptr, nullptr, nullptr},
        {"Calibre 10 Racing", A, nullptr, nullptr, nullptr},
        {"Chime Sharp", A, nullptr, nullptr, nullptr},
        {"Cities XL Platinum", A, nullptr, nullptr, "Cities XL"},
        {"Coffin Dodgers", A, nullptr, nullptr, nullptr},
        {"Company of Heroes 2", A, nullptr, nullptr, nullptr},
        {"Dark", A, nullptr, nullptr, nullptr},
        {"Dark Void", A, nullptr, nullptr, nullptr},
        {"Daylight", A, nullptr, nullptr, nullptr},
        {"Deadfall Adventures", A, nullptr, nullptr, nullptr},
        {"Defenders of Time", A, nullptr, nullptr, nullptr},
        {"Defense Grid: The Awakening", A, nullptr, nullptr, nullptr},
        {"Defense Grid: Containment", A, nullptr, nullptr, nullptr},
        {"Descent: Underground", C | A, nullptr, nullptr, nullptr},
        {"Diluvion", A, nullptr, nullptr, nullptr},
        {"Dungeon Defenders Eternity", A, nullptr, nullptr, nullptr},
        {"Dungeon Defenders II", A, nullptr, nullptr, nullptr},
        {"Dungeon Siege III", A, nullptr, nullptr, nullptr},
        {"Dungeons", A, nullptr, nullptr, nullptr},
        {"Dungeons - The Dark Lord", A, nullptr, nullptr, nullptr},
        {"Dungeons & Dragons Online", A, nullptr, nullptr, nullptr},
        {"Dying Light: Bad Blood", A, nullptr, nullptr, nullptr},
        {"Dyscourse", A, nullptr, nullptr, nullptr},
        {"Elegy for a Dead World", A, nullptr, nullptr, nullptr},
        {"Enter the Gungeon", A, nullptr, nullptr, nullptr},
        {"EVE Online", A, nullptr, nullptr, nullptr},
        {"Eximius: Seize the Frontline", A, nullptr, nullptr, nullptr},
        {"Fable III", A, nullptr, nullptr, nullptr},
        {"Factions: Origins of Malu", A, nullptr, nullptr, nullptr},
        {"Fallen Earth", A, nullptr, nullptr, nullptr},
        {"Forced Showdown", A, nullptr, nullptr, nullptr},
        {"Fort Triumph", A, nullptr, nullptr, nullptr},
        {"Forts", A, nullptr, nullptr, nullptr},
        {"Fractal Space", A, nullptr, nullptr, nullptr},
        {"Gauntlet", A, nullptr, nullptr, "Gauntlet Slayer Edition"},
        {"Girls Like Robots", A, nullptr, nullptr, nullptr},
        {"GRIP: Combat Racing", A, nullptr, nullptr, "GRIP"},
        {"Gunscape", A, nullptr, nullptr, nullptr},
        {"Guts and Glory", A, nullptr, nullptr, nullptr},
        {"Hacknet", A, nullptr, nullptr, nullptr},
        {"Hamilton's Great Adventure", A, nullptr, nullptr, nullptr},
        {"Haunted House", A, nullptr, nullptr, nullptr},
        {"Heroes Must Die", A, nullptr, nullptr, nullptr},
        {"Holodrive", A, nullptr, nullptr, nullptr},
        {"Hotline Miami", A, nullptr, nullptr, nullptr},
        {"HyperBrawl Tournament", A, nullptr, nullptr, nullptr},
        {"Imagine Me", A, nullptr, nullptr, nullptr},
        {"Knight Squad", A, nullptr, nullptr, nullptr},
        {"Krater", A, nullptr, nullptr, nullptr},
        {"Kursk", A, nullptr, nullptr, nullptr},
        {"Lead and Gold: Gangs of the Wild West", A, nullptr, nullptr, "Lead and Gold"},
        {"Lightstep Chronicles", A, nullptr, nullptr, nullptr},
        {"The Lord of the Rings: War in the North", A, nullptr, nullptr, nullptr},
        {"The Lord of the Rings Online", A, nullptr, nullptr, nullptr},
        {"Lords of New York", A, nullptr, nullptr, nullptr},
        {"Lovely Planet", A, nullptr, nullptr, nullptr},
        {"MAV", A, nullptr, nullptr, nullptr},
        {"Magic: The Gathering - Duels of the Planeswalkers 2012", A, nullptr, nullptr, nullptr},
        {"Magic: The Gathering - Duels of the Planeswalkers 2013", A, nullptr, nullptr, nullptr},
        {"Magic: The Gathering - Duels of the Planeswalkers 2014", A, nullptr, nullptr, nullptr},
        {"MechRunner", A, nullptr, nullptr, nullptr},
        {"Metro: Last Light", A, nullptr, nullptr, "Metro: Last Light Redux"},
        {"Metro 2033", A, nullptr, nullptr, "Metro 2033 Redux"},
        {"MicroVolts Surge", A, nullptr, nullptr, nullptr},
        {"Middle-earth: Shadow of Mordor", A, nullptr, nullptr, nullptr},
        {"Mr. Shifty", A, nullptr, nullptr, nullptr},
        {"Mushroom Men: Truffle Trouble", A, nullptr, nullptr, nullptr},
        {"Neverending Nightmares", A, nullptr, nullptr, nullptr},
        {"Nexuiz", A, nullptr, nullptr, nullptr},
        {"No Time to Explain", A, nullptr, nullptr, "No Time To Explain Remastered"},
        {"Orcs Must Die! 2", A, nullptr, nullptr, nullptr},
        {"Orion Ark", A, nullptr, nullptr, nullptr},
        {"Overlord II", A, nullptr, nullptr, nullptr},
        {"Overture", A, nullptr, nullptr, nullptr},
        {"Painkiller Hell & Damnation", A, nullptr, nullptr, nullptr},
        {"Paladins", A, nullptr, nullptr, nullptr},
        {"Party Golf", A, nullptr, nullptr, nullptr},
        {"Party Hard", A, nullptr, nullptr, nullptr},
        {"Party Hard 2", A, nullptr, nullptr, nullptr},
        {"Party Hard Tycoon", A, nullptr, nullptr, nullptr},
        {"PAYDAY: The Heist", A, nullptr, nullptr, nullptr},
        {"Primal Carnage: Extinction", A, nullptr, nullptr, nullptr},
        {"Quantum Conundrum", A, nullptr, nullptr, nullptr},
        {"Race The Sun", A, nullptr, nullptr, nullptr},
        {"Ravaged", A, nullptr, nullptr, nullptr},
        {"Rekoil", A, nullptr, nullptr, nullptr},
        {"Rend", A, nullptr, nullptr, nullptr},
        {"Robot Roller-Derby Disco Dodgeball", A, nullptr, nullptr, nullptr},
        {"RollerCoaster Tycoon World", A, nullptr, nullptr, nullptr},
        {"Ronin", A, nullptr, nullptr, nullptr},
        {"Rusty Hearts", A, nullptr, nullptr, nullptr},
        {"Sacred 2 Gold", A, nullptr, nullptr, "Sacred 2"},
        {"Serious Sam 3: BFE", A, nullptr, nullptr, nullptr},
        {"Shadow Warrior", A, nullptr, nullptr, nullptr},
        {"SMITE", A, nullptr, nullptr, nullptr},
        {"Sniper Elite 4", A, nullptr, nullptr, nullptr},
        {"Sniper Ghost Warrior Contracts", A, nullptr, nullptr, nullptr},
        {"Spacecom", A, nullptr, nullptr, nullptr},
        {"Space Pirates and Zombies", A, nullptr, nullptr, "SPAZ"},
        {"Special Forces: Team X", A, nullptr, nullptr, nullptr},
        {"Stagelight", A, nullptr, nullptr, nullptr},
        {"Streets of Rogue", A, nullptr, nullptr, nullptr},
        {"Super Dungeon Bros", A, nullptr, nullptr, nullptr},
        {"Supreme Commander 2", A, nullptr, nullptr, nullptr},
        {"Switchblade", A, nullptr, nullptr, nullptr},
        {"The Counting Kingdom", A, nullptr, nullptr, nullptr},
        {"The Gardens Between", A, nullptr, nullptr, nullptr},
        {"The Talos Principle", A, nullptr, nullptr, nullptr},
        {"The Town of Light", A, nullptr, nullptr, nullptr},
        {"The Witcher 2: Assassins of Kings", A, nullptr, nullptr, "The Witcher 2: Assassins of Kings Enhanced Edition"},
        {"The Witcher: Enhanced Edition", A, nullptr, nullptr, nullptr},
        {"This War of Mine", A, nullptr, nullptr, nullptr},
        {"Torn Tales", A, nullptr, nullptr, nullptr},
        {"Totally Reliable Delivery Service", A, nullptr, nullptr, nullptr},
        {"Tower 57", A, nullptr, nullptr, nullptr},
        {"Transcripted", A, nullptr, nullptr, nullptr},
        {"Tribes: Ascend", A, nullptr, nullptr, nullptr},
        {"Underworld Ascendant", A, nullptr, nullptr, nullptr},
        {"Victor Vran", A, nullptr, nullptr, "Victor Vran ARPG"},
        {"Void Invaders", A, nullptr, nullptr, nullptr},
        {"Warhammer Quest", A, nullptr, nullptr, nullptr},
        {"Warhammer: End Times - Vermintide", A, nullptr, nullptr, nullptr},
        {"Winning Putt", A, nullptr, nullptr, nullptr},
        {"XCOM: Enemy Unknown", A, nullptr, nullptr, nullptr},
        {"Yonder: The Cloud Catcher Chronicles", A, nullptr, nullptr, nullptr},
        {"Zombie Party", A, nullptr, nullptr, nullptr},
        {"Zombie Playground", A, nullptr, nullptr, nullptr},
    };
    *count = sizeof kGames / sizeof kGames[0];
    return kGames;
}

}  // namespace luma::app::games
